optimizer:
  type: AdamW
  lr: 1e-3
  betas:
    - 0.9
    - 0.999
  weight_decay: 0.1
  constructor: LayerDecayOptimizerConstructor
  paramwise_cfg:
    num_layers: 12
    layer_decay_rate: 0.9998 # 1-2e-4
    custom_keys:
      bias:
        decay_multi: 0.0
      pos_embed:
        decay_mult: 0.0
      relative_position_bias_table:
        decay_mult: 0.0
      norm:
        decay_mult: 0.0

optimizer_config:
  grad_clip:
    max_norm: 1.0
    norm_type: 2

lr_config:
  policy: step
  warmup: linear
  warmup_iters: 300
  warmup_ratio: 0.001
  step:
    - 3

total_epochs: 4

data_config: &data_config
  image_size:
    - 192
    - 256
  heatmap_size:
    - 48
    - 64
  normalization:
    mean:
      - 0.485
      - 0.456
      - 0.406
    std:
      - 0.229
      - 0.224
      - 0.225

  soft_nms: False
  nms_thr: 1.0
  oks_thr: 0.9
  vis_thr: 0.2
  use_gt_bbox: False
  det_bbox_thr: 0.0
  bbox_file: 'data/coco/person_detection_results/COCO_val2017_detections_AP_H_56_person.json'

data_root: '/home/adryw/dataset/COCO17'

data:
  samples_per_gpu: 64
  workers_per_gpu: 6
  val_dataloader:
    samples_per_gpu: 128
  test_dataloader:
    samples_per_gpu: 128
  train:
    type: TopDownCocoDataset
    ann_file: '${data_root}/annotations/person_keypoints_train2017.json'
    img_prefix: '${data_root}/train2017/'
    data_cfg: *data_config
  val:
    type: TopDownCocoDataset
    ann_file: '${data_root}/annotations/person_keypoints_val2017.json'
    img_prefix: '${data_root}/val2017/'
    data_cfg: *data_config
  test:
    type: TopDownCocoDataset
    ann_file: '${data_root}/annotations/person_keypoints_val2017.json'
    img_prefix: '${data_root}/val2017/'
    data_cfg: *data_config

model_small: &model_definition
  type: TopDown
  pretrained: null
  backbone:
    type: ViT
    img_size:
      - 256
      - 192
    patch_size: 16
    embed_dim: 384
    depth: 12
    num_heads: 12
    ratio: 1
    use_checkpoint: False
    mlp_ratio: 4
    qkv_bias: True
    drop_path_rate: 0.1
  keypoint_head:
    type: TopdownHeatmapSimpleHead
    in_channels: 384
    num_deconv_layers: 2
    num_deconv_filters:
      - 256
      - 256
    num_deconv_kernels:
      - 4
      - 4
    extra:
      final_conv_kernel: 1
    loss_keypoint:
      type: JointsMSELoss
      use_target_weight: True
  train_cfg: {}
  test_cfg:
    flip_test: True
    post_process: default
    shift_heatmap: False
    target_type: GaussianHeatmap
    modulate_kernel: 11
    use_udp: True

model_base:
  <<: *model_definition
  backbone:
    embed_dim: 768
    drop_path_rate: 0.3


model_large:
  <<: *model_definition
  backbone:
    num_heads: 16
    depth: 24
    embed_dim: 1024
    drop_path_rate: 0.5


model_huge:
  <<: *model_definition
  backbone:
    num_heads: 16
    depth: 32
    embed_dim: 1280
    drop_path_rate: 0.55
