name: "COCO25"
keypoints_shape: [25, 3]

keypoints:
  0: "nose"
  1: "left_eye"
  2: "right_eye"
  3: "left_ear"
  4: "right_ear"
  5: "neck"
  6: "left_shoulder"
  7: "right_shoulder"
  8: "left_elbow"
  9: "right_elbow"
  10: "left_wrist"
  11: "right_wrist"
  12: "left_hip"
  13: "right_hip"
  14: "hip"
  15: "left_knee"
  16: "right_knee"
  17: "left_ankle"
  18: "right_ankle"
  19: "left_big toe"
  20: "left_small_toe"
  21: "left_heel"
  22: "right_big_toe"
  23: "right_small_toe"
  24: "right_heel"

skeleton:
  - [17, 15]
  - [15, 12]
  - [18, 16]
  - [16, 13]
  - [12, 14]
  - [13, 14]
  - [5, 14]
  - [6, 5]
  - [7, 5]
  - [6, 8]
  - [7, 9]
  - [8, 10]
  - [9, 11]
  - [1, 2]
  - [0, 1]
  - [0, 2]
  - [1, 3]
  - [2, 4]
  - [17, 21]
  - [18, 24]
  - [19, 20]
  - [22, 23]
  - [19, 21]
  - [22, 24]
  - [5, 0]

names:
  0: person
